# -*- coding: utf-8 -*-
"""IoT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fyqSMyLGbNyiFgf2yVW_YFQ1vuAQYVgJ
"""

import pandas as pd
import numpy as np

df=pd.read_csv('feeds_data.csv')
df.head()

df=df.iloc[31:,:]

df=df.dropna(axis=1)
df.head()

df=df.drop('created_at',axis=1)
df.head()

df=df.drop('entry_id',axis=1)

df.head()

X=df.iloc[:,:-1].values
Y=df.iloc[:,-1].values

Y

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.22, random_state = 0)

X_train

from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = "entropy", random_state = 0)
classifier.fit(X_train, y_train)

y_pred=classifier.predict(X_test)

# np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)

# from sklearn.metrics import confusion_matrix, accuracy_score
# cm = confusion_matrix(y_test, y_pred)
# cm
# accuracy_score(y_test, y_pred)

def pred(a,b,c,d,e,f,g):
    return classifier.predict([[a,b,c,d,e,f,g]])